### ISSUE TITLE
Authenticated cluster

### ISSUE THREAD

**Issue by jmlambert78** [leportlabs/mongo-k8s-sidecar#10]
Hi,
I have used the sidecar application to see the automatic config of a Replicaset.
The mongod are started in a non auth mode, and I wonder whether if you looked at this.
I tried to create an admin account, then I changed the template to include --auth and restart the containers. It seems not working.
Thx for your answers.

**Comment by cvallance** [comment]
Hi @jmlambert78, could you please explain in a little more detail what you are trying to attempt and what the issue / error you are getting exactly. Cheers, Charles.

**Comment by jmlambert78** [comment]
For sure, In fact I start a replica set with the sidecar. 
Then I should add the authentication steps with the additional of a cluster manager etc.
And next step is to restart the mongod with the --auth activated.
when I do that, the sidecar cannot authenticate to perform actions, so my question is which steps to make to integrate this fully 
Thx for your support

**Comment by cvallance** [comment]
Thanks! So from what I remember (and can see), it's currently setup to only connect via localhost (127.0.0.1). We could look at making the change, but I'm really not sure when we can get to it... more than happy to accept a pull request to make the change!

You'll want to look at `worker.js` and line #36 where connecting to the mongo database is done... then I'd suggest altering `config.js` to return a mongo connection string that is constructed via env vars.
