### ISSUE TITLE
Great project! Any way to use it with persistentVolumes

### ISSUE THREAD

**Issue by teknologist** [leportlabs/mongo-k8s-sidecar#3]
For example NFS.

The problem is that all mongo containers in each pod share the same directory.
I have been desperate to parametrize the volumePath in the replication controller and haven't found any solution yet!

Can you be of any help ?

Many thanks!

Eric

**Comment by teknologist** [comment]
I have included hostname in dbpath but as every time the kubernetes cluster is restarted, hostnames change so I have to reconfigure the replica set. It's a real pain.

**Comment by cvallance** [comment]
I haven't got a good solution for you I'm afraid. When writing this we were experimenting with putting mongo in k8s but honestly, we never found it to be satisfactory. We ending up putting mongo on their own machines.

**Comment by thesandlord** [comment]
I'm experimenting with running a Replica Set in Kubernetes with PVs. Each Replica gets its own Replication Controller, which is not ideal but I still want to try. 

I don't think it's possible to use PVs with something like this (that can auto-scale Pods) without Kubernetes supporting a more flexible storage backend interface.
